commonAnnotations:
  helm.sh/hook: crd-install
  helm.sh/hook-delete-policy: before-hook-creation

resources:
  - crossplane/templates/crds/packages.crossplane.io_clusterpackageinstalls.yaml
  - crossplane/templates/crds/packages.crossplane.io_packageinstalls.yaml
