apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gkeclusters.container.gcp.conductor.io
spec:
  group: container.gcp.conductor.io
  names:
    kind: GKECluster
    plural: gkeclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              items:
                type: string
              type: array
            async:
              type: boolean
            clusterSecondaryRangeName:
              type: string
            clusterVersion:
              type: string
            connectionSecretRef:
              type: object
            createSubnetwork:
              type: object
            diskSize:
              type: string
            enableAutorepair:
              type: boolean
            enableAutoscaling:
              type: boolean
            enableAutoupgrade:
              type: boolean
            enableBasicAuth:
              type: boolean
            enableCloudEndpoints:
              type: boolean
            enableCloudLogging:
              type: boolean
            enableCloudMonitoring:
              type: boolean
            enableIPAlias:
              type: boolean
            enableKubernetesAlpha:
              type: boolean
            enableLegacyAuthorization:
              type: boolean
            enableNetworkPolicy:
              type: boolean
            imageType:
              type: string
            labels:
              type: object
            localSSDCount:
              format: int64
              type: integer
            machineType:
              type: string
            maintenanceWindow:
              type: string
            maxNodes:
              format: int64
              type: integer
            maxNodesPerPool:
              format: int64
              type: integer
            minCPUPlatform:
              type: string
            minNodes:
              format: int64
              type: integer
            network:
              type: string
            noIssueClientCertificates:
              type: boolean
            nodeLabels:
              items:
                type: string
              type: array
            nodeLocations:
              items:
                type: string
              type: array
            nodeTaints:
              items:
                type: string
              type: array
            nodeVersion:
              items:
                type: string
              type: array
            numNodes:
              format: int64
              type: integer
            password:
              type: string
            preemtible:
              type: boolean
            providerRef:
              type: object
            scopes:
              items:
                type: string
              type: array
            serviceAccount:
              type: string
            serviceSecondaryRangeName:
              type: string
            subnetwork:
              type: string
            tags:
              items:
                type: string
              type: array
            username:
              type: string
            zone:
              type: string
          required:
          - clusterVersion
          - machineType
          - numNodes
          - zone
          - providerRef
          - connectionSecretRef
          type: object
        status:
          properties:
            message:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
