
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: compositeresourcedefinitions.apiextensions.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: apiextensions.crossplane.io
  names:
    categories:
    - crossplane
    kind: CompositeResourceDefinition
    listKind: CompositeResourceDefinitionList
    plural: compositeresourcedefinitions
    shortNames:
    - xrd
    singular: compositeresourcedefinition
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: An CompositeResourceDefinition defines a new kind of composite infrastructure resource. The new resource is composed of other composite or managed infrastructure resources.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CompositeResourceDefinitionSpec specifies the desired state of the definition.
          properties:
            claimNames:
              description: ClaimNames specifies the names of an optional composite resource claim. When claim names are specified Crossplane will create a namespaced 'composite resource claim' CRD that corresponds to the defined composite resource. This composite resource claim acts as a namespaced proxy for the composite resource; creating, updating, or deleting the claim will create, update, or delete a corresponding composite resource. You may add claim names to an existing CompositeResourceDefinition, but they cannot be changed once they have been set.
              properties:
                categories:
                  description: categories is a list of grouped resources this custom resource belongs to (e.g. 'all'). This is published in API discovery documents, and used by clients to support invocations like `kubectl get all`.
                  items:
                    type: string
                  type: array
                kind:
                  description: kind is the serialized kind of the resource. It is normally CamelCase and singular. Custom resource instances will use this value as the `kind` attribute in API calls.
                  type: string
                listKind:
                  description: listKind is the serialized kind of the list for this resource. Defaults to "`kind`List".
                  type: string
                plural:
                  description: plural is the plural name of the resource to serve. The custom resources are served under `/apis/<group>/<version>/.../<plural>`. Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`). Must be all lowercase.
                  type: string
                shortNames:
                  description: shortNames are short names for the resource, exposed in API discovery documents, and used by clients to support invocations like `kubectl get <shortname>`. It must be all lowercase.
                  items:
                    type: string
                  type: array
                singular:
                  description: singular is the singular name of the resource. It must be all lowercase. Defaults to lowercased `kind`.
                  type: string
              required:
              - kind
              - plural
              type: object
            connectionSecretKeys:
              description: ConnectionSecretKeys is the list of keys that will be exposed to the end user of the defined kind.
              items:
                type: string
              type: array
            crdSpecTemplate:
              description: CRDSpecTemplate is the base CRD template. The final CRD will have additional fields to the base template to accommodate Crossplane machinery.
              properties:
                additionalPrinterColumns:
                  description: additionalPrinterColumns specifies additional columns returned in Table output. See https://kubernetes.io/docs/reference/using-api/api-concepts/#receiving-resources-as-tables for details. If present, this field configures columns for all versions. Top-level and per-version columns are mutually exclusive. If no top-level or per-version columns are specified, a single column displaying the age of the custom resource is used.
                  items:
                    description: CustomResourceColumnDefinition specifies a column for server side printing.
                    properties:
                      JSONPath:
                        description: JSONPath is a simple JSON path (i.e. with array notation) which is evaluated against each custom resource to produce the value for this column.
                        type: string
                      description:
                        description: description is a human readable description of this column.
                        type: string
                      format:
                        description: format is an optional OpenAPI type definition for this column. The 'name' format is applied to the primary identifier column to assist in clients identifying column is the resource name. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.
                        type: string
                      name:
                        description: name is a human readable name for the column.
                        type: string
                      priority:
                        description: priority is an integer defining the relative importance of this column compared to others. Lower numbers are considered higher priority. Columns that may be omitted in limited space scenarios should be given a priority greater than 0.
                        format: int32
                        type: integer
                      type:
                        description: type is an OpenAPI type definition for this column. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types for details.
                        type: string
                    required:
                    - JSONPath
                    - name
                    - type
                    type: object
                  type: array
                group:
                  description: group is the API group of the defined custom resource. The custom resources are served under `/apis/<group>/...`. Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`).
                  type: string
                names:
                  description: names specify the resource and kind names for the custom resource.
                  properties:
                    categories:
                      description: categories is a list of grouped resources this custom resource belongs to (e.g. 'all'). This is published in API discovery documents, and used by clients to support invocations like `kubectl get all`.
                      items:
                        type: string
                      type: array
                    kind:
                      description: kind is the serialized kind of the resource. It is normally CamelCase and singular. Custom resource instances will use this value as the `kind` attribute in API calls.
                      type: string
                    listKind:
                      description: listKind is the serialized kind of the list for this resource. Defaults to "`kind`List".
                      type: string
                    plural:
                      description: plural is the plural name of the resource to serve. The custom resources are served under `/apis/<group>/<version>/.../<plural>`. Must match the name of the CustomResourceDefinition (in the form `<names.plural>.<group>`). Must be all lowercase.
                      type: string
                    shortNames:
                      description: shortNames are short names for the resource, exposed in API discovery documents, and used by clients to support invocations like `kubectl get <shortname>`. It must be all lowercase.
                      items:
                        type: string
                      type: array
                    singular:
                      description: singular is the singular name of the resource. It must be all lowercase. Defaults to lowercased `kind`.
                      type: string
                  required:
                  - kind
                  - plural
                  type: object
                validation:
                  description: validation describes the schema used for validation and pruning of the custom resource. If present, this validation schema is used to validate all versions. Top-level and per-version schemas are mutually exclusive.
                  properties:
                    openAPIV3Schema:
                      description: openAPIV3Schema is the OpenAPI v3 schema to use for validation and pruning.
                      type: object
                  type: object
                version:
                  description: 'version is the API version of the defined custom resource. The custom resources are served under `/apis/<group>/<version>/...`. Must match the name of the first item in the `versions` list if `version` and `versions` are both specified. Optional if `versions` is specified. Deprecated: use `versions` instead.'
                  type: string
              required:
              - group
              - names
              type: object
            defaultCompositionRef:
              description: DefaultCompositionRef refers to the Composition resource that will be used in case no composition selector is given.
              properties:
                name:
                  description: Name of the referenced object.
                  type: string
              required:
              - name
              type: object
            enforcedCompositionRef:
              description: EnforcedCompositionRef refers to the Composition resource that will be used by all composite instances whose schema is defined by this definition.
              properties:
                name:
                  description: Name of the referenced object.
                  type: string
              required:
              - name
              type: object
          type: object
        status:
          description: CompositeResourceDefinitionStatus shows the observed state of the definition.
          properties:
            conditions:
              description: Conditions of the resource.
              items:
                description: A Condition that may apply to a resource.
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the last time this condition transitioned from one status to another.
                    format: date-time
                    type: string
                  message:
                    description: A Message containing details about this condition's last transition from one status to another, if any.
                    type: string
                  reason:
                    description: A Reason for this condition's last transition from one status to another.
                    type: string
                  status:
                    description: Status of this condition; is it currently True, False, or Unknown?
                    type: string
                  type:
                    description: Type of this condition. At most one of each condition type may apply to a resource at any point in time.
                    type: string
                required:
                - lastTransitionTime
                - reason
                - status
                - type
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
