# This file is used to define a custom transformer for our CRDs so that Kustomize
# can change the cross-resource object references when the referred object's
# name changes.
# See https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/crd/README.md
nameReference:
  - kind: Network
    fieldSpecs:
      - path: spec/networkRef/name
        kind: Connection
  - kind: Provider
    fieldSpecs:
      - path: spec/providerRef/name
        kind: Connection