apiVersion: storage.crossplane.io/v1alpha1
kind: MySQLInstance
metadata:
  name: sql
  namespace: complex
spec:
  classReference:
    name: standard-mysql
    namespace: crossplane-system
  engineVersion: "5.7"
---
apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplication
metadata:
  name: wordpress-demo
  namespace: complex
  labels:
    app: wordpress-demo
spec:
  resourceSelector:
    matchLabels:
      app: wordpress-demo
  clusterSelector:
    matchLabels:
      app: wordpress-demo
  resourceTemplates:
  - metadata:
      name: wordpress-demo-namespace
      labels:
        app: wordpress-demo
    spec:
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: wordpress
          labels:
            app: wordpress
  - metadata:
      name: wordpress-demo-deployment
      labels:
        app: wordpress-demo
    spec:
      secrets:
      - name: sql  # Resource claim secret name is derived from claim name
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: wordpress
          name: wordpress
          labels:
            app: wordpress
        spec:
          selector:
            matchLabels:
              app: wordpress
          template:
            metadata:
              labels:
                app: wordpress
            spec:
              containers:
                - name: wordpress
                  image: wordpress:4.6.1-apache
                  env:
                    - name: WORDPRESS_DB_HOST
                      valueFrom:
                        secretKeyRef:
                          name: wordpress-demo-deployment-sql
                          key: endpoint
                    - name: WORDPRESS_DB_USER
                      valueFrom:
                        secretKeyRef:
                          name: wordpress-demo-deployment-sql
                          key: username
                    - name: WORDPRESS_DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: wordpress-demo-deployment-sql
                          key: password
                  ports:
                    - containerPort: 80
                      name: wordpress
  - metadata:
      name: wordpress-demo-service
      labels:
        app: wordpress-demo
    spec:
      template:
        apiVersion: v1
        kind: Service
        metadata:
          namespace: wordpress
          name: wordpress
          labels:
            app: wordpress
        spec:
          ports:
            - port: 80
          selector:
            app: wordpress
          type: LoadBalancer
