---
apiVersion: compute.gcp.crossplane.io/v1alpha2
kind: GlobalAddress
metadata:
  name: sample-globaladdress
spec:
  name: my-cool-globaladdress
  purpose: VPC_PEERING
  addressType: INTERNAL
  prefixLength: 16
  networkRef:
    name: sample-network
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
