---
apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: Network
metadata:
  name: sample-network
spec:
  name: my-cool-network
  autoCreateSubnetworks: false
  routingConfig:
    routingMode: REGIONAL
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
