apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: rdsinstances.database.aws.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.bindingPhase
    name: STATUS
    type: string
  - JSONPath: .status.state
    name: STATE
    type: string
  - JSONPath: .spec.classRef.name
    name: CLASS
    type: string
  - JSONPath: .spec.engineVersion
    name: VERSION
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: database.aws.crossplane.io
  names:
    kind: RDSInstance
    plural: rdsinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            claimRef:
              description: Kubernetes object references
              type: object
            class:
              type: string
            classRef:
              type: object
            connectionSecretRef:
              type: object
            engine:
              type: string
            engineVersion:
              type: string
            masterUsername:
              type: string
            providerRef:
              type: object
            reclaimPolicy:
              description: ReclaimPolicy identifies how to handle the cloud resource
                after the deletion of this type
              type: string
            securityGroups:
              description: "VPC Security groups that will allow the RDS instance to
                be accessed over the network. You can consider the following groups:
                1) A default group that allows all communication amongst instances
                in that group 2) A RDS specific group that allows port 3306 from allowed
                sources (clients and instances \t  that are expected to connect to
                the database."
              items:
                type: string
              type: array
            size:
              description: like "db.t2.micro"
              format: int64
              type: integer
            subnetGroupName:
              description: Specifies a DB subnet group for the DB instance. The new
                DB instance is created in the VPC associated with the DB subnet group.
                If no DB subnet group is specified, then the new DB instance is not
                created in a VPC.
              type: string
          required:
          - masterUsername
          - engine
          - class
          - size
          - providerRef
          type: object
        status:
          properties:
            endpoint:
              description: the generated DB Instance name
              type: string
            instanceName:
              description: the external ID to identify this resource in the cloud
                provider
              type: string
            message:
              type: string
            providerID:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
