apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName  | quote }}
      {{- end }}
      {{- if not .Values.hostedConfig.enabled }}
      serviceAccountName: {{ template "name" . }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        {{- range $arg := .Values.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
          {{- toYaml .Values.resourcesCrossplane | nindent 12 }}
      {{- if .Values.hostedConfig.enabled }}
        env:
          - name: KUBERNETES_SERVICE_HOST
            value: {{ .Values.hostedConfig.tenantKubernetesServiceHost | quote }}
          - name: KUBERNETES_SERVICE_PORT
            value: {{ .Values.hostedConfig.tenantKubernetesServicePort | quote }}
        volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: sa-token
            readOnly: true
      automountServiceAccountToken: false
      serviceAccount: ""
      serviceAccountName: ""
      volumes:
        - name: sa-token
          secret:
            defaultMode: 420
            secretName: {{ .Values.hostedConfig.crossplaneSATokenSecret | quote }}
      {{- end }}