apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crossplane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "crossplane.name" . }}
    release: {{ .Release.Name }}
    {{- include "crossplane.labels" . | indent 4 }}
  {{- with .Values.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "crossplane.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      {{- if or .Values.metrics.enabled .Values.customAnnotations }}
      annotations:
      {{- end }}
      {{- if .Values.metrics.enabled }}
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      {{- end }}
      {{- with .Values.customAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "crossplane.name" . }}
        release: {{ .Release.Name }}
        {{- include "crossplane.labels" . | indent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContextCrossplane | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName  | quote }}
      {{- end }}
      serviceAccountName: {{ template "crossplane.name" . }}
      initContainers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
          - core
          - init
          {{- range $arg := .Values.provider.packages }}
          - --provider
          - "{{ $arg }}"
          {{- end }}
          {{- range $arg := .Values.configuration.packages }}
          - --configuration
          - "{{ $arg }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-init
          resources:
            {{- toYaml .Values.resourcesCrossplane | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContextCrossplane | nindent 12 }}
          env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}-init
                resource: limits.cpu
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}-init
                resource: limits.memory
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          {{- if .Values.webhooks.enabled }}
          - name: "WEBHOOK_TLS_SECRET_NAME"
            value: webhook-tls-secret
          - name: "WEBHOOK_SERVICE_NAME"
            value: {{ template "crossplane.name" . }}-webhooks
          - name: "WEBHOOK_SERVICE_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: "WEBHOOK_SERVICE_PORT"
            value: "9443"
          {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - core
        - start
        {{- range $arg := .Values.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
          {{- toYaml .Values.resourcesCrossplane | nindent 12 }}
        {{- if or .Values.metrics.enabled (.Values.webhooks.enabled) }}
        ports:
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          containerPort: 8080
        {{- end }}
        {{- if .Values.webhooks.enabled }}
        - name: webhooks
          containerPort: 9443
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContextCrossplane | nindent 12 }}
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: limits.cpu
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: limits.memory
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LEADER_ELECTION
            value: "{{ .Values.leaderElection }}"
          {{- if .Values.registryCaBundleConfig.key }}
          - name: CA_BUNDLE_PATH
            value: "/certs/{{ .Values.registryCaBundleConfig.key }}"
          {{- end}}
          {{- if .Values.webhooks.enabled }}
          - name: "WEBHOOK_TLS_SECRET_NAME"
            value: webhook-tls-secret
          - name: "WEBHOOK_TLS_CERT_DIR"
            value: /webhook/tls
          {{- end }}
        {{- range $key, $value := .Values.extraEnvVarsCrossplane }}
          - name: {{ $key | replace "." "_" }}
            value: {{ $value | quote }}
        {{- end}}
        volumeMounts:
          - mountPath: /cache
            name: package-cache
          {{- if .Values.registryCaBundleConfig.name }}
          - mountPath: /certs
            name: ca-certs
          {{- end }}
          {{- if .Values.webhooks.enabled }}
          - mountPath: /webhook/tls
            name: webhook-tls-secret
          {{- end }}
      {{- if .Values.xfn.enabled }}
      - image: {{ .Values.xfn.image.repository }}:{{ .Values.xfn.image.tag }}
        args:
        - start
        {{- range $arg := .Values.xfn.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.xfn.image.pullPolicy }}
        name: {{ .Chart.Name }}-xfn
        resources:
          {{- toYaml .Values.xfn.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.xfn.securityContext | nindent 12 }}
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: limits.cpu
          - name: GOMEMLIMIT
            valueFrom:
              resourceFieldRef:
                containerName: {{ .Chart.Name }}
                resource: limits.memory
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        {{- range $key, $value := .Values.xfn.extraEnvVars }}
          - name: {{ $key | replace "." "_" }}
            value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
          - mountPath: /xfn
            name: xfn-cache
      {{- end }}
      volumes:
      - name: package-cache
        {{- if .Values.packageCache.pvc }}
        persistentVolumeClaim:
          claimName: {{ .Values.packageCache.pvc }}
        {{- else if .Values.packageCache.configMap }}
        configMap:
          name: {{ .Values.packageCache.configMap }}
        {{- else }}
        emptyDir:
          medium: {{ .Values.packageCache.medium }}
          sizeLimit: {{ .Values.packageCache.sizeLimit }}
        {{- end }}
      {{- if .Values.xfn.enabled }}
      - name: xfn-cache
        {{- if .Values.xfn.cache.pvc }}
        persistentVolumeClaim:
          claimName: {{ .Values.xfn.cache.pvc }}
        {{- else }}
        emptyDir:
          medium: {{ .Values.xfn.cache.medium }}
          sizeLimit: {{ .Values.xfn.cache.sizeLimit }}
        {{- end }}
      {{- end }}
      {{- if .Values.registryCaBundleConfig.name }}
      - name: ca-certs
        configMap:
          name: {{ .Values.registryCaBundleConfig.name }}
          items:
            - key: {{ .Values.registryCaBundleConfig.key }}
              path: {{ .Values.registryCaBundleConfig.key }}
      {{- end }}
      {{- if .Values.webhooks.enabled }}
      - name: webhook-tls-secret
        secret:
          # NOTE(muvaf): The tls.crt is used both by the server (requires it to
          # be a single cert) and the caBundle fields of webhook configs and CRDs
          # which can accept a whole bundle of certificates. In order to meet
          # the requirements of both, we require a single certificate instead of
          # a bundle.
          # It's assumed that initializer generates this anyway, so it should be
          # fine.
          secretName: webhook-tls-secret
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
