apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crossplane.name" . }}
  labels:
    app: {{ template "crossplane.name" . }}
    release: {{ .Release.Name }}
    {{- include "crossplane.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "crossplane.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      {{- end }}
      labels:
        app: {{ template "crossplane.name" . }}
        release: {{ .Release.Name }}
        {{- include "crossplane.labels" . | indent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContextCrossplane | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName  | quote }}
      {{- end }}
      serviceAccountName: {{ template "crossplane.name" . }}
      initContainers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
          - core
          - init
          {{- range $arg := .Values.provider.packages }}
          - --provider
          - "{{ $arg }}"
          {{- end }}
          {{- range $arg := .Values.configuration.packages }}
          - --configuration
          - "{{ $arg }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-init
          resources:
            {{- toYaml .Values.resourcesCrossplane | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContextCrossplane | nindent 12 }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - core
        - start
        {{- range $arg := .Values.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources:
          {{- toYaml .Values.resourcesCrossplane | nindent 12 }}
        {{- if .Values.metrics.enabled }}
        ports:
        - name: metrics
          containerPort: 8080
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContextCrossplane | nindent 12 }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LEADER_ELECTION
            value: "{{ .Values.leaderElection }}"
          {{- if .Values.registryCaBundleConfig.key }}
          - name: CA_BUNDLE_PATH
            value: "/certs/{{ .Values.registryCaBundleConfig.key }}"
          {{- end}}
        {{- range $key, $value := .Values.extraEnvVarsCrossplane }}
          - name: {{ $key | replace "." "_" }}
            value: {{ $value | quote }}
        {{- end}}
        volumeMounts:
          - mountPath: /cache
            name: package-cache
            {{- if .Values.registryCaBundleConfig.name }}
          - mountPath: /certs
            name: ca-certs
            {{- end }}
      volumes:
      - name: package-cache
        {{- if .Values.packageCache.pvc }}
        persistentVolumeClaim:
          claimName: {{ .Values.packageCache.pvc }}
        {{- else }}
        emptyDir:
          medium: {{ .Values.packageCache.medium }}
          sizeLimit: {{ .Values.packageCache.sizeLimit }}
        {{- end }}
      {{- if .Values.registryCaBundleConfig.name }}
      - name: ca-certs
        configMap:
          name: {{ .Values.registryCaBundleConfig.name }}
          items:
            - key: {{ .Values.registryCaBundleConfig.key }}
              path: {{ .Values.registryCaBundleConfig.key }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}