{{- if .Values.personas.deploy }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}:stack-manager:ns:default:admin
  labels:
    rbac.crossplane.io/aggregate-to-namespace-default-admin: "true"
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - cache.crossplane.io
  - compute.crossplane.io
  - database.crossplane.io
  - kubernetes.crossplane.io
  - core.crossplane.io
  - storage.crossplane.io
  - workload.crossplane.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - stacks.crossplane.io
  resources:
  - stackinstalls
  - stacks
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}:stack-manager:ns:default:edit
  labels:
    rbac.crossplane.io/aggregate-to-namespace-default-admin: "true"
    rbac.crossplane.io/aggregate-to-namespace-default-edit: "true"
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - cache.crossplane.io
  - compute.crossplane.io
  - database.crossplane.io
  - kubernetes.crossplane.io
  - core.crossplane.io
  - storage.crossplane.io
  - workload.crossplane.io
  resources:
  - "*"
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}:stack-manager:ns:default:view
  labels:
    rbac.crossplane.io/aggregate-to-namespace-default-edit: "true"
    rbac.crossplane.io/aggregate-to-namespace-default-view: "true"
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - cache.crossplane.io
  - compute.crossplane.io
  - database.crossplane.io
  - kubernetes.crossplane.io
  - core.crossplane.io
  - stacks.crossplane.io
  - storage.crossplane.io
  - workload.crossplane.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stacks.crossplane.io
  resources:
  - stacks
  - stackinstalls
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}:system:ns-persona-cluster-rights
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
{{- end}}
