apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "crossplane.name" . }}
  labels:
    app: {{ template "crossplane.name" . }}
    {{- include "crossplane.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range $index, $secret := .Values.imagePullSecrets }}
- name: {{ $secret }}
{{- end }}
{{ end }}
