---
apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplication
metadata:
  name: wordpress-demo
  namespace: complex
  labels:
    app: wordpress-demo
spec:
  resourceSelector:
    matchLabels:
      app: wordpress-demo
  clusterSelector:
    matchLabels:
      app: wordpress-demo
  resourceTemplates:
    - metadata:
        name: wordpress-demo-namespace
        labels:
          app: wordpress-demo
      spec:
        template:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: wordpress
            labels:
              app: wordpress
    - metadata:
        name: wordpress-demo-deployment
        labels:
          app: wordpress-demo
      spec:
        secrets:
          # This must match the writeConnectionSecretToRef field
          # on the database claim; it is the name of the secret to
          # pull from the crossplane cluster, from this Application's namespace.
          - name: sql
        template:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: wordpress
            name: wordpress
            labels:
              app: wordpress
          spec:
            selector:
              matchLabels:
                app: wordpress
            template:
              metadata:
                labels:
                  app: wordpress
              spec:
                containers:
                  - name: wordpress
                    image: wordpress:4.6.1-apache
                    env:
                      - name: WORDPRESS_DB_HOST
                        valueFrom:
                          secretKeyRef:
                            # This is the name of the secret to use to consume the secret
                            # within the managed cluster. The reason it's different from the
                            # name of the secret above is because within the managed cluster,
                            # a crossplane-managed secret is written as '{metadata.name}-{secretname}'.
                            # The metadata name is specified above for this resource, and so is
                            # the secret name.
                            name: wordpress-demo-deployment-sql
                            key: endpoint
                      - name: WORDPRESS_DB_USER
                        valueFrom:
                          secretKeyRef:
                            name: wordpress-demo-deployment-sql
                            key: username
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: wordpress-demo-deployment-sql
                            key: password
                    ports:
                      - containerPort: 80
                        name: wordpress
    - metadata:
        name: wordpress-demo-service
        labels:
          app: wordpress-demo
      spec:
        template:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: wordpress
            name: wordpress
            labels:
              app: wordpress
          spec:
            ports:
              - port: 80
            selector:
              app: wordpress
            type: LoadBalancer
