---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: wordpress-demo-cluster
  labels:
    app: wordpress-demo
spec:
  writeConnectionSecretToRef:
    name: wordpress-demo-cluster
