apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: containers.storage.azure.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.accountRef.name
    name: STORAGE_ACCOUNT
    type: string
  - JSONPath: .spec.publicAccessType
    name: PUBLIC_ACCESS_TYPE
    type: string
  - JSONPath: .spec.classRef.name
    name: CLASS
    type: string
  - JSONPath: .spec.reclaimPolicy
    name: RECLAIM_POLICY
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: storage.azure.crossplane.io
  names:
    kind: Container
    plural: containers
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            accountRef:
              type: object
            claimRef:
              type: object
            classRef:
              type: object
            connectionSecretNameOverride:
              description: ConnectionSecretNameOverride to generate connection secret
                with specific name
              type: string
            nameFormat:
              description: NameFormat to format container name passing it a object
                UID If not provided, defaults to "%s", i.e. UID value
              type: string
            providerRef:
              type: object
            publicAccessType:
              type: string
            reclaimPolicy:
              description: ReclaimPolicy identifies how to handle the cloud resource
                after the deletion of this type
              type: string
          required:
          - accountRef
          - providerRef
          type: object
        status:
          properties:
            connectionSecretRef:
              type: object
            name:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
