---
apiVersion: identity.aws.crossplane.io/v1alpha3
kind: IAMRole
metadata:
  name: sample-eks-cluster-role
spec:
  roleName: my-cool-eks-cluster-role
  description: a role that gives a cool power
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "eks.amazonaws.com"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
