---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: InternetGateway
metadata:
  name: sample-internetgateway
spec:
  vpcIdRef:
    name: sample-vpc
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
