---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: SecurityGroup
metadata:
  name: sample-rds-sg
spec:
  vpcIdRef:
    name: sample-vpc
  groupName: my-cool-rds-sg
  description: open rds access to crossplane workload
  reclaimPolicy: Delete
  ingress:
    - fromPort: 3306
      toPort: 3306
      protocol: tcp
      cidrBlocks:
        - cidrIp: 0.0.0.0/0
          description: all ips
  providerRef:
    name: aws-provider
