---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: sample-subnet1
spec:
  cidrBlock: 192.168.64.0/18
  vpcIdRef:
    name: sample-vpc
  availabilityZone: us-west-2a
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: sample-subnet2
spec:
  cidrBlock: 192.168.128.0/18
  vpcIdRef:
    name: sample-vpc
  availabilityZone: us-west-2b
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: sample-subnet3
spec:
  cidrBlock: 192.168.192.0/18
  vpcIdRef:
    name: sample-vpc
  availabilityZone: us-west-2c
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
