---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: VPC
metadata:
  name: sample-vpc
spec:
  cidrBlock: 192.168.0.0/16
  enableDnsSupport: true
  enableDnsHostNames: true
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
