apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gkeclusters.compute.gcp.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.bindingPhase
    name: STATUS
    type: string
  - JSONPath: .status.state
    name: STATE
    type: string
  - JSONPath: .status.clusterName
    name: CLUSTER-NAME
    type: string
  - JSONPath: .status.endpoint
    name: ENDPOINT
    type: string
  - JSONPath: .spec.classRef.name
    name: CLUSTER-CLASS
    type: string
  - JSONPath: .spec.zone
    name: LOCATION
    type: string
  - JSONPath: .spec.reclaimPolicy
    name: RECLAIM-POLICY
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: compute.gcp.crossplane.io
  names:
    kind: GKECluster
    plural: gkeclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              items:
                type: string
              type: array
            async:
              type: boolean
            claimRef:
              type: object
            classRef:
              type: object
            clusterSecondaryRangeName:
              type: string
            clusterVersion:
              type: string
            createSubnetwork:
              type: boolean
            diskSize:
              type: string
            enableAutorepair:
              type: boolean
            enableAutoscaling:
              type: boolean
            enableAutoupgrade:
              type: boolean
            enableBasicAuth:
              type: boolean
            enableCloudEndpoints:
              type: boolean
            enableCloudLogging:
              type: boolean
            enableCloudMonitoring:
              type: boolean
            enableIPAlias:
              type: boolean
            enableKubernetesAlpha:
              type: boolean
            enableLegacyAuthorization:
              type: boolean
            enableNetworkPolicy:
              type: boolean
            imageType:
              type: string
            labels:
              type: object
            localSSDCount:
              format: int64
              type: integer
            machineType:
              type: string
            maintenanceWindow:
              type: string
            maxNodes:
              format: int64
              type: integer
            maxNodesPerPool:
              format: int64
              type: integer
            minCPUPlatform:
              type: string
            minNodes:
              format: int64
              type: integer
            network:
              type: string
            noIssueClientCertificates:
              type: boolean
            nodeLabels:
              items:
                type: string
              type: array
            nodeLocations:
              items:
                type: string
              type: array
            nodeTaints:
              items:
                type: string
              type: array
            nodeVersion:
              items:
                type: string
              type: array
            numNodes:
              format: int64
              type: integer
            password:
              type: string
            preemtible:
              type: boolean
            providerRef:
              type: object
            reclaimPolicy:
              type: string
            scopes:
              items:
                type: string
              type: array
            serviceAccount:
              type: string
            serviceSecondaryRangeName:
              type: string
            subnetwork:
              type: string
            tags:
              items:
                type: string
              type: array
            username:
              type: string
            writeConnectionSecretToRef:
              type: object
            zone:
              type: string
          required:
          - providerRef
          type: object
        status:
          properties:
            clusterName:
              type: string
            endpoint:
              type: string
            state:
              type: string
          required:
          - clusterName
          - endpoint
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
