apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: gkeclusters.compute.gcp.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.bindingPhase
    name: STATUS
    type: string
  - JSONPath: .status.state
    name: STATE
    type: string
  - JSONPath: .status.clusterName
    name: CLUSTER-NAME
    type: string
  - JSONPath: .status.endpoint
    name: ENDPOINT
    type: string
  - JSONPath: .spec.classRef.name
    name: CLUSTER-CLASS
    type: string
  - JSONPath: .spec.zone
    name: LOCATION
    type: string
  - JSONPath: .spec.reclaimPolicy
    name: RECLAIM-POLICY
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: compute.gcp.crossplane.io
  names:
    kind: GKECluster
    plural: gkeclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            addons:
              items:
                type: string
              type: array
            async:
              description: --adons
              type: boolean
            claimRef:
              description: Kubernetes object references
              type: object
            classRef:
              type: object
            clusterSecondaryRangeName:
              description: --cluster-ipv4-cidr
              type: string
            clusterVersion:
              description: --cluster-secondary-range-name
              type: string
            connectionSecretRef:
              type: object
            createSubnetwork:
              description: --cluster-version
              type: object
            diskSize:
              description: --create-subnetwork
              type: string
            enableAutorepair:
              description: --disk-size
              type: boolean
            enableAutoscaling:
              description: Cluster Autoscaling
              type: boolean
            enableAutoupgrade:
              description: --enable-autorepair
              type: boolean
            enableBasicAuth:
              description: --password
              type: boolean
            enableCloudEndpoints:
              description: --service-account
              type: boolean
            enableCloudLogging:
              description: --enable-autoupgrade
              type: boolean
            enableCloudMonitoring:
              description: --no-enable-cloud-logging]
              type: boolean
            enableIPAlias:
              description: --no-enable-cloud-monitoring
              type: boolean
            enableKubernetesAlpha:
              description: --enable-ip-alias
              type: boolean
            enableLegacyAuthorization:
              description: --enable-kubernetes-alpha
              type: boolean
            enableNetworkPolicy:
              description: --enable-legacy-authorization
              type: boolean
            imageType:
              description: --enable-network-policy
              type: string
            labels:
              description: --no-issue-client-certificate
              type: object
            localSSDCount:
              description: --labels
              format: int64
              type: integer
            machineType:
              description: --local-ssd-count
              type: string
            maintenanceWindow:
              description: --machine-types
              type: string
            maxNodes:
              description: --enable-autoscaling
              format: int64
              type: integer
            maxNodesPerPool:
              description: '--maintenance-window, example: ''12:43'''
              format: int64
              type: integer
            minCPUPlatform:
              description: --max-nodes-per-pool
              type: string
            minNodes:
              description: --max-nodes
              format: int64
              type: integer
            network:
              description: --min-cpu-platform
              type: string
            noIssueClientCertificates:
              description: --image-type
              type: boolean
            nodeLabels:
              description: --network
              items:
                type: string
              type: array
            nodeLocations:
              description: --node-labels [NODE_LABEL,因
              items:
                type: string
              type: array
            nodeTaints:
              description: --node-locations=ZONE,[ZONE,因
              items:
                type: string
              type: array
            nodeVersion:
              description: --node-taints=[NODE_TAINT,因
              items:
                type: string
              type: array
            numNodes:
              description: --node-version=NODE_VERSION
              format: int64
              type: integer
            password:
              description: Basic Auth
              type: string
            preemtible:
              description: --num-nodes=NUM_NODES; default=3
              type: boolean
            providerRef:
              type: object
            reclaimPolicy:
              description: ReclaimPolicy identifies how to handle the cloud resource
                after the deletion of this type
              type: string
            scopes:
              description: --enable-cloud-endpoints
              items:
                type: string
              type: array
            serviceAccount:
              description: Node Identity
              type: string
            serviceSecondaryRangeName:
              description: --services-ipv4-cidr=CIDR
              type: string
            subnetwork:
              description: --services-secondary-range-name=NAME
              type: string
            tags:
              description: --subnetwork=SUBNETWORK
              items:
                type: string
              type: array
            username:
              description: --enable-basic-auth
              type: string
            zone:
              description: --tags=TAG,[TAG,因
              type: string
          type: object
        status:
          properties:
            clusterName:
              type: string
            endpoint:
              type: string
            state:
              type: string
          required:
          - clusterName
          - endpoint
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
