apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: cloudsqlinstances.database.gcp.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.bindingPhase
    name: STATUS
    type: string
  - JSONPath: .status.state
    name: STATE
    type: string
  - JSONPath: .spec.classRef.name
    name: CLASS
    type: string
  - JSONPath: .spec.databaseVersion
    name: VERSION
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: database.gcp.crossplane.io
  names:
    kind: CloudsqlInstance
    plural: cloudsqlinstances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            databaseVersion:
              description: The database engine (MySQL or PostgreSQL) and its specific
                version to use, e.g., MYSQL_5_7 or POSTGRES_9_6.
              type: string
            region:
              type: string
            storageGB:
              format: int64
              type: integer
            storageType:
              type: string
            tier:
              description: MySQL and PostgreSQL use different machine types.  MySQL
                only allows a predefined set of machine types, while PostgreSQL can
                only use custom machine instance types and shared-core instance types.
                For the full set of MySQL machine types, see https://cloud.google.com/sql/pricing#2nd-gen-instance-pricing.
                For more information on custom machine types that can be used with
                PostgreSQL, see the examples on https://cloud.google.com/sql/docs/postgres/create-instance?authuser=1#machine-types
                and the naming rules on https://cloud.google.com/sql/docs/postgres/create-instance#create-2ndgen-curl.
              type: string
          required:
          - region
          - storageType
          - storageGB
          - databaseVersion
          - tier
          type: object
        status:
          properties:
            endpoint:
              description: Endpoint of the Cloud SQL instance used in connection strings.
              type: string
            instanceName:
              description: Name of the Cloud SQL instance. This does not include the
                project ID.
              type: string
            message:
              type: string
            providerID:
              description: the external ID to identify this resource in the cloud
                provider
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
