---
apiVersion: v1
kind: Namespace
metadata:
  name: complex
---
apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: wordpress-demo-cluster
  namespace: complex
  labels:
    app: wordpress-demo
spec:
  writeConnectionSecretToRef:
    name: wordpress-demo-cluster
  classRef:
    kind: GKEClusterClass
    apiVersion: compute.gcp.crossplane.io/v1alpha2
    name: standard-cluster
    namespace: crossplane-system
