apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: buckets.storage.crossplane.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.bindingPhase
    name: STATUS
    type: string
  - JSONPath: .spec.classReference.name
    name: CLASS
    type: string
  - JSONPath: .spec.predefinedACL
    name: PREDEFINED-ACL
    type: string
  - JSONPath: .spec.localPermission
    name: LOCAL-PERMISSION
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  group: storage.crossplane.io
  names:
    kind: Bucket
    plural: buckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            classReference:
              type: object
            connectionSecretNameOverride:
              maxLength: 255
              minLength: 1
              type: string
            localPermission:
              description: LocalPermission is the permissions granted on the bucket
                for the provider specific bucket service account that is available
                in a secret after provisioning.
              enum:
              - Read
              - Write
              - ReadWrite
              type: string
            name:
              description: Bucket properties
              maxLength: 63
              minLength: 3
              type: string
            predefinedACL:
              enum:
              - Private
              - PublicRead
              - PublicReadWrite
              - AuthenticatedRead
              type: string
            resourceName:
              type: object
            selector:
              type: object
          type: object
        status:
          properties:
            credentialsSecret:
              description: CredentialsSecretRef is a local reference to the generated
                secret containing the credentials for this resource claim.
              type: object
            provisioner:
              description: 'Provisioner is the driver that was used to provision the
                concrete resource This is an optionally-prefixed name, like a label
                key. For example: "RDSInstance.database.aws.crossplane.io/v1alpha1"
                or "CloudSQLInstance.database.gcp.crossplane.io/v1alpha1".'
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
