apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-package-manager
  labels:
    app: {{ template "name" . }}-package-manager
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-package-manager
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-package-manager
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      serviceAccountName: package-manager
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
        - package
        - manage
        {{- if .Values.hostedConfig.enabled }}
        - --tenant-kubeconfig
        - /var/run/secrets/tenant/kubeconfig
        - --host-controller-namespace
        - {{ .Values.hostedConfig.controllerNamespace | quote }}
        {{- end }}
        {{- if .Values.templateStacks.enabled }}
        - --templates
        {{- if .Values.templateStacks.controllerImage }}
        - --templating-controller-image
        - {{ .Values.templateStacks.controllerImage | quote }}
        {{- end }}
        {{- end }}
        {{- if .Values.forceImagePullPolicy }}
        - --force-image-pull-policy
        - {{ .Values.forceImagePullPolicy | quote }}
        {{- end }}
        {{- if .Values.insecureAllowAllApigroups }}
        - --insecure-allow-all-apigroups
        {{- end }}
        {{- if .Values.insecurePassFullDeployment }}
        - --insecure-pass-full-deployment
        {{- end }}
        {{- range $arg := .Values.args }}
        - {{ $arg }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        env:
        # The pod name to pass with the downward API
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # The pod namespace to pass with the downward API
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.resourcesPackageManager | nindent 12 }}
      {{- if .Values.hostedConfig.enabled }}
        volumeMounts:
          - mountPath: /var/run/secrets/tenant
            name: tenant-config
            readOnly: true
      volumes:
        - name: tenant-config
          secret:
            defaultMode: 420
            secretName: {{ .Values.hostedConfig.tenantKubeconfigSecret | quote }}
      {{- end }}
