name: Configurations

on:
  push:
    branches:
      - master
      - release-*
  workflow_dispatch: {}

env:
  DOCKER_USR: ${{ secrets.UPBOUND_XP_ROBOT_USR }}

jobs:
  getting-started-with-aws:
    runs-on: ubuntu-22.04
    if: github.repository == 'crossplane/crossplane'
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          submodules: true
          fetch-depth: 0
      # The tagger step uses the same logic in the build submodule to generate package tag
      # https://github.com/upbound/build/blob/4f64913157a952dbe77cd9e05457d9abe695a1d4/makelib/common.mk#L193
      - name: Set tag
        run: echo "VERSION_TAG=$(git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )" >> $GITHUB_OUTPUT
        id: tagger
      - name: Login to Docker
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.UPBOUND_XP_ROBOT_USR }}
          password: ${{ secrets.UPBOUND_XP_ROBOT_PSW }}
      - name: Build
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          channel: master
          version: current
          command: build configuration -f cluster/packages/aws --name=getting-started-with-aws.xpkg
      - name: Push
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          command: push configuration -f cluster/packages/aws/getting-started-with-aws.xpkg registry.upbound.io/xp/getting-started-with-aws:${{ steps.tagger.outputs.VERSION_TAG }}

  getting-started-with-aws-with-vpc:
    runs-on: ubuntu-22.04
    if: github.repository == 'crossplane/crossplane'
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set tag
        run: echo "VERSION_TAG=$(git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )" >> $GITHUB_OUTPUT
        id: tagger
      - name: Login to Docker
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.UPBOUND_XP_ROBOT_USR }}
          password: ${{ secrets.UPBOUND_XP_ROBOT_PSW }}
      - name: Build
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          channel: master
          version: current
          command: build configuration -f cluster/packages/aws-with-vpc --name=getting-started-with-aws-with-vpc.xpkg
      - name: Push
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          command: push configuration -f cluster/packages/aws-with-vpc/getting-started-with-aws-with-vpc.xpkg registry.upbound.io/xp/getting-started-with-aws-with-vpc:${{ steps.tagger.outputs.VERSION_TAG }}

  getting-started-with-gcp:
    runs-on: ubuntu-22.04
    if: github.repository == 'crossplane/crossplane'
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set tag
        run: echo "VERSION_TAG=$(git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )" >> $GITHUB_OUTPUT
        id: tagger
      - name: Login to Docker
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.UPBOUND_XP_ROBOT_USR }}
          password: ${{ secrets.UPBOUND_XP_ROBOT_PSW }}
      - name: Build
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          channel: master
          version: current
          command: build configuration -f cluster/packages/gcp --name=getting-started-with-gcp.xpkg
      - name: Push
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          command: push configuration -f cluster/packages/gcp/getting-started-with-gcp.xpkg registry.upbound.io/xp/getting-started-with-gcp:${{ steps.tagger.outputs.VERSION_TAG }}

  getting-started-with-azure:
    runs-on: ubuntu-22.04
    if: github.repository == 'crossplane/crossplane'
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Set tag
        run: echo "VERSION_TAG=$(git describe --dirty --always --tags | sed 's/-/./2' | sed 's/-/./2' )" >> $GITHUB_OUTPUT
        id: tagger
      - name: Login to Docker
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2
        if: env.DOCKER_USR != ''
        with:
          registry: registry.upbound.io
          username: ${{ secrets.UPBOUND_XP_ROBOT_USR }}
          password: ${{ secrets.UPBOUND_XP_ROBOT_PSW }}
      - name: Build
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          channel: master
          version: current
          command: build configuration -f cluster/packages/azure --name=getting-started-with-azure.xpkg
      - name: Push
        uses: crossplane-contrib/xpkg-action@1696d9091687aad2895436cb5656faa956628b0f # v0.2.0
        with:
          command: push configuration -f cluster/packages/azure/getting-started-with-azure.xpkg registry.upbound.io/xp/getting-started-with-azure:${{ steps.tagger.outputs.VERSION_TAG }}
