name: PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  checklist-completed:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-22.04
    steps:
      - uses: mheap/require-checklist-action@01fe24747f8630a056d9ca79dfbbb755579850ab # v2
        with:
          # The checklist must _exist_ and be filled out.
          requireChecklist: true