---
apiVersion: compute.gcp.crossplane.io/v1alpha3
kind: GKEClusterClass
metadata:
  name: standard-cluster
  annotations:
    resourceclass.crossplane.io/is-default-class: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  machineType: n1-standard-1
  numNodes: 1
  zone: us-central1-b
  networkRef:
    name: sample-network
  subnetworkRef:
    name: sample-subnetwork
  enableIPAlias: true
  clusterSecondaryRangeName: pods
  servicesSecondaryRangeName: services
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
